# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# streamdelineate.py
# Created on: 2023-07-27 19:14:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: streamdelineate <Input_surface_raster> <Threshold> <Output_Stream_Network> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
Input_surface_raster = arcpy.GetParameterAsText(0)

Threshold = arcpy.GetParameterAsText(1)

Output_Stream_Network = arcpy.GetParameterAsText(2)
if Output_Stream_Network == '#' or not Output_Stream_Network:
    Output_Stream_Network = "C:\\Users\\new\\Documents\\TemporaryFolder\\StreamOfinal.shp" # provide a default value if unspecified

# Local variables:
FillDem_tif = "%Value%\\FillDem.tif"
Output_drop_raster = ""
FlowDir_tif = "%Value%\\FlowDir.tif"
FlowAcc_tif = "%Value%\\FlowAcc.tif"
threshold_tif = "%Value%\\threshold.tif"
streamO_tif = "%Value%\\streamO.tif"
Value = "C:\\Users\\new\\Documents\\TemporaryFolder"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "%Workspace%"
arcpy.env.workspace = "%Workspace%"

# Process: Fill
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\Users\\new\\Documents\\ArcGIS\\Default.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "C:\\Users\\new\\Documents\\ArcGIS\\Default.gdb"
arcpy.gp.Fill_sa(Input_surface_raster, FillDem_tif, "")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(FillDem_tif, FlowDir_tif, "NORMAL", Output_drop_raster, "D8")

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(FlowDir_tif, FlowAcc_tif, "", "FLOAT", "D8")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("\"%FlowAcc.tif%\" >= %Threshold%", threshold_tif)

# Process: Stream Order
arcpy.gp.StreamOrder_sa(threshold_tif, FlowDir_tif, streamO_tif, "STRAHLER")

# Process: Stream to Feature
arcpy.gp.StreamToFeature_sa(streamO_tif, FlowDir_tif, Output_Stream_Network, "SIMPLIFY")

# Process: Parse Path
arcpy.ParsePath_mb(Output_Stream_Network, "PATH")

